openapi: 3.0.1
info:
  # Schema version
  version: 1.0.0
  title: Data Foundation
  description: Test Demo
paths: {}
components:
  schemas:
    DataFoundationEvent:
      type: object
      required:
        - event
        - ts
        - payload
      properties:
        event:
          $ref: "#/components/schemas/EventName"
        ts:
          type: integer
          format: int64
        payload:
          $ref: "#/components/schemas/EventPayload"
    EventPayload:
      type: object
      required:
        - device_hash
        - ts
        - app_start_time
        - seq_no
        - app_name
        - app_version
        - reporting_version
        - app_release
        - app_build
        - platform
        - experiments
        - state_indicators
        - country_vl
        - os
        - os_version
        - sim_country
        - device_language
        - manufacturer
        - brand
        - model
        - carrier
        - screen_dpi
        - screen_height
        - screen_width
        - eventType
      properties:
        device_hash:
          type: string
        ts:
          type: integer
          format: int64
        app_start_time:
          type: integer
          format: int64
        seq_no:
          type: integer
        app_name:
          type: string
        app_version:
          type: string
        reporting_version:
          type: string
          enum: ["1.0.0"]
        app_release:
          type: integer
        app_build:
          type: string
        platform:
          $ref: "#/components/schemas/PlatformType"
        experiments:
          type: string
        state_indicators:
          $ref: "#/components/schemas/StateIndicators"
        country_vl:
          type: string
        os:
          type: string
        os_version:
          type: string
        notes:
          type: string
        sim_country:
          type: string
        device_language:
          type: string
        manufacturer:
          type: string
        brand:
          type: string
        model:
          type: string
        carrier:
          type: string
        screen_dpi:
          type: integer
        screen_height:
          type: integer
        screen_width:
          type: integer
        eventType:
          type: string
      discriminator:
        propertyName: eventType
    UiViewEventPayload:
      allOf:
        - $ref: "#/components/schemas/EventPayload"
        - type: object
          properties:
            action_source:
              $ref: "#/components/schemas/ActionId"
            view_source:
              $ref: "#/components/schemas/ViewId"
            view_detail:
              type: string
            view_version:
              type: string
            view_name:
              $ref: "#/components/schemas/ViewId"
    UiActionEventPayload:
      allOf:
        - $ref: "#/components/schemas/EventPayload"
        - type: object
          properties:
            action_detail:
              type: string
            action_name:
              $ref: "#/components/schemas/ActionId"
            action_source:
              $ref: "#/components/schemas/ActionId"
            view_detail:
              type: string
            view_version:
              type: string
            view_name:
              $ref: "#/components/schemas/ViewId"
            view_source:
              $ref: "#/components/schemas/ViewId"
            sku:
              type: string
    AppStartEventPayload:
      allOf:
        - $ref: "#/components/schemas/EventPayload"
        - type: object
          properties:
            source:
              $ref: "#/components/schemas/LaunchSource"
            dist_channel:
              type: string
            android_gs_ver:
              type: string
    AppAttributionEventPayload:
      allOf:
        - $ref: "#/components/schemas/EventPayload"
        - type: object
          properties:
            source:
              $ref: "#/components/schemas/AttributionSource"
            dist_channel:
              type: string
    PlatformType:
      enum: [ios, android, macos, windows, chrome]
    LaunchSource:
      enum:
        - foreground
        - launch
    AttributionSource:
      enum:
        - kochava
    StateIndicators:
      type: object
      properties:
        fg_permission_on:
          type: boolean
        unknown_sources_enabled:
          type: boolean
        vpn_permission_on:
          type: boolean
        vpn_on:
          type: boolean
        user_status:
          $ref: "#/components/schemas/UserStatus"
        extra_packages:
          type: string
    EventName:
      enum:
        - ui_view
        - ui_action
        - app_start
        - app_attribution
    UserStatus:
      enum:
        - free
        - trial
        - premium
    ViewId:
      enum:
        - dlg_connection_rate
        - dlg_forgot_password
        - dlg_rate
        - dlg_vl_explanation
        - ntf_invalid_email
        - ntf_no_connection
        - scn_about
        - scn_account
        - scn_bad_connection_feedback
        - scn_bad_connection_options
        - scn_bad_connection_thanks
        - scn_bundle
        - scn_create_account
        - scn_dashboard
        - scn_data_consent
        - scn_forgot_password
        - scn_go_browse
        - scn_optin
        - scn_paywall
        - scn_policy_updating
        - scn_privacy_policy
        - scn_profile
        - scn_settings
        - scn_sign_in
        - scn_source_attributions
        - scn_splash
        - scn_vl_country_select
        - scn_vpn_config
    ActionId:
      enum:
        - btn_about
        - btn_account
        - btn_allow
        - btn_back
        - btn_blog
        - btn_bundle
        - btn_cancel
        - btn_close
        - btn_connect
        - btn_create_account
        - btn_dashboard
        - btn_feedback
        - btn_forgot_password
        - btn_get
        - btn_help
        - btn_manage_account
        - btn_not_allow
        - btn_ok
        - btn_open
        - btn_paywall
        - btn_privacy_policy
        - btn_proceed_basic
        - btn_profile
        - btn_rate
        - btn_reinstall_profile
        - btn_reset_password
        - btn_restore_purchase
        - btn_review
        - btn_settings
        - btn_sign_in
        - btn_sign_out
        - btn_source_attributions
        - btn_start_subscription
        - btn_start_trial
        - btn_submit
        - btn_terms_apply
        - btn_terms_of_service
        - btn_upgrade
        - btn_vl_change
        - btn_vl_info
        - ncl_pango_banner
        - scr_source_attributions
        - swp_close
        - swp_vl_change