openapi: 3.0.1
info:
  # Schema version
  version: 0.0.1
  title: Data Foundation
  description: Test Demo
paths: {}
components:
  schemas:
    DataFoundationEvent:
      type: object
      description: Base Event
      required:
        - device_hash
        - ts
        - app_start_time
        - seq_no
        - app_name
        - app_version
        - reporting_version
        - app_release
        - app_build
        - platform
        - experiments
        - state_indicators
        - country_vl
        - os
        - os_version
        - eventType
      properties:
        device_hash:
          type: string
        ts:
          type: integer
          format: int64
        app_start_time:
          type: integer
          format: int64
        seq_no:
          type: integer
        app_name:
          type: string
        app_version:
          type: string
        reporting_version:
          type: string
        app_release:
          type: string
        app_build:
          type: string
        platform:
          $ref: "#/definitions/PlatformType"
        experiments:
          type: string
        state_indicators:
          $ref: "#/definitions/StateIndicators"
        country_vl:
          type: string
        os:
          type: string
        os_version:
          type: string
        notes:
          type: string
        eventType:
          type: string
      discriminator:
        propertyName: eventType
    DeviceProperties:
      type: object
      properties:
        sim_country:
          type: string
        device_language:
          type: string
        store_country:
          type: string
        app_language:
          type: string
        manufacturer:
          type: string
        brand:
          type: string
        model:
          type: string
        carrier:
          type: string
        screen_height:
          type: integer
        screen_width:
          type: integer
    UiViewEvent:
      allOf:
        - $ref: "#/components/schemas/DataFoundationEvent"
        - type: object
          properties:
            action_source:
              $ref: "#/definitions/ActionID"
            view_source:
              $ref: "#/definitions/ViewID"
            view_detail:
              type: string
            view_version:
              type: string
            view_name:
              $ref: "#/definitions/ViewID"
    UiActionEvent:
      allOf:
        - $ref: "#/components/schemas/DataFoundationEvent"
        - type: object
          properties:
            action_detail:
              type: string
            action_name:
              $ref: "#/definitions/ActionID"
            action_source:
              $ref: "#/definitions/ActionID"
            view_detail:
              type: string
            view_version:
              type: string
            view_name:
              $ref: "#/definitions/ViewID"
            view_source:
              $ref: "#/definitions/ViewID"
            sku:
              type: string
    AppStartEvent:
      allOf:
        - $ref: "#/components/schemas/DataFoundationEvent"
        - $ref: "#/definitions/DeviceProperties"
        - type: object
          properties:
            source:
              $ref: "#/definitions/LaunchSource"
    AppAttributionEvent:
      allOf:
        - $ref: "#/components/schemas/DataFoundationEvent"
        - $ref: "#/definitions/DeviceProperties"
        - type: object
          properties:
            source:
              $ref: "#/definitions/AttributionSource"
    ApiResponseEvent:
      allOf:
        - $ref: "#/components/schemas/DataFoundationEvent"
        - type: object
          properties:
            token:
              type: string
            network_hash:
              type: string
            source:
              $ref: "#/definitions/ApiResponseSource"
            api_id:
              type: string
            duration:
              type: integer
            error_code:
              type: integer
            error:
              type: string
            sd_id:
              type: string
            unified_sd:
              type: string
            sd_config_source:
              type: string
            sd_in_tunnel:
              type: string
            network_availability:
              type: string
    PlatformType:
      enum: [ios, android, macos, windows, chrome]
    LaunchSource:
      enum:
        - foreground
        - launch
    AttributionSource:
      enum:
        - adjust
        - kochava
    ApiResponseSource:
      enum:
        - cdms
        - elite
        - mydati
    StateIndicators:
      type: object
      properties:
        fg_permission_on:
          type: boolean
        unknown_sources_enabled:
          type: boolean
        vpn_permission_on:
          type: boolean
        vpn_on:
          type: boolean
        tracker_blocking_on:
          type: boolean
        website_blocking_on:
          type: boolean
        ad_blocking_on:
          type: boolean
        user_status:
          $ref: "#/definitions/UserStatus"
        extra_packages:
          type: string
    UserStatus:
      enum:
        - free
        - trial
        - premium
    ViewID:
      enum:
        - dlg_connection_rate
        - dlg_forgot_password
        - dlg_rate
        - dlg_vl_explanation
        - ntf_invalid_email
        - ntf_no_connection
        - scn_about
        - scn_account
        - scn_bad_connection_feedback
        - scn_bad_connection_options
        - scn_bad_connection_thanks
        - scn_bundle
        - scn_create_account
        - scn_dashboard
        - scn_data_consent
        - scn_forgot_password
        - scn_go_browse
        - scn_optin
        - scn_paywall
        - scn_policy_updating
        - scn_privacy_policy
        - scn_profile
        - scn_settings
        - scn_sign_in
        - scn_source_attributions
        - scn_splash
        - scn_vl_country_select
        - scn_vpn_config
    ActionID:
      enum:
        - btn_about
        - btn_account
        - btn_allow
        - btn_back
        - btn_blog
        - btn_bundle
        - btn_cancel
        - btn_close
        - btn_connect
        - btn_create_account
        - btn_dashboard
        - btn_feedback
        - btn_forgot_password
        - btn_get
        - btn_help
        - btn_manage_account
        - btn_not_allow
        - btn_ok
        - btn_open
        - btn_paywall
        - btn_privacy_policy
        - btn_proceed_basic
        - btn_profile
        - btn_rate
        - btn_reinstall_profile
        - btn_reset_password
        - btn_restore_purchase
        - btn_review
        - btn_settings
        - btn_sign_in
        - btn_sign_out
        - btn_source_attributions
        - btn_start_subscription
        - btn_start_trial
        - btn_submit
        - btn_terms_apply
        - btn_terms_of_service
        - btn_upgrade
        - btn_vl_change
        - btn_vl_info
        - ncl_pango_banner
        - scr_source_attributions
        - swp_close
        - swp_vl_change