swagger: "2.0"
info:
  # Schema version
  version: 0.0.1
  title: Data Foundation
  description: Test Demo
title: Events
definitions:
  # BaseEvent should be inherited by other events. It contains basic super properties required in each event.
  BaseEvent:
    discriminator: eventType
    type: object
    description: Base Event
    required:
      - device_hash
      - client_ts
      - seq_no
      - app_name
      - app_version
      - reporting_version
      - platform
    properties:
      device_hash:
        type: string
      client_ts:
        type: integer
        format: int64
      seq_no:
        type: integer
      app_name:
        type: string
      app_version:
        type: string
      reporting_version:
        type: string
        # FIXME: figure another way.
        # defaultValue + custom mustache template
        enum: ['0.0.1']
      platform:
        type: string
        enum: [ios, android]
      eventType:
        type: string
        default: 'BaseEvent'
  UiClick:
    type: object
    description: UI Click event
    allOf:
      - $ref: '#/definitions/BaseEvent'
      - required:
          - is_premium
          - event_name
        properties:
          event_name:
            type: string
            enum: ['ui_click']
          is_premium:
            type: integer
          experiments:
            type: object
          notes:
            type: object
